# Generated by Django 5.0 on 2024-01-16 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionVehicular', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'default_related_name': 'personales', 'managed': True},
        ),
    ]
