# Generated by Django 5.0 on 2024-01-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionVehicular', '0002_alter_personal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='id',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
