# Generated by Django 5.0 on 2024-01-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appGestionVehicular', '0003_alter_personal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReclamoSugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuito', models.CharField(blank=True, max_length=55, null=True)),
                ('subcircuito', models.CharField(blank=True, max_length=55, null=True)),
                ('reclamo_sugerencia', models.CharField(blank=True, max_length=150, null=True)),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('contacto', models.IntegerField(blank=True, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('nombres', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'reclamo_sugerencia',
                'managed': False,
            },
        ),
    ]
